oddam_w_dobre_rece/urls.py
from django.contrib import admin
from django.urls import path

import main.views as Main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Main.LadingPageView.as_view(), name='landing-page'),
    path('add_donation', Main.AddDonationView.as_view(), name='add-donation-page'),
    path('register', Main.RegisterView.as_view(), name='register-page'),
    path('login', Main.LoginView.as_view(), name='login-page'),
    path('logout', Main.logout_view, name='logout-page'),
    path('profil', Main.UserProfileView.as_view(), name='profile-page'),
    path('settings', Main.UserSettingsView.as_view(), name='settings-page'),
    path('donation_confirm', Main.takenConfirm, name='confirm-page'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

FOUNDATION = 0
NON_GOV = 1
LOCAL_COLLECTION = 2

INSTITUTION_CHOICE = {
    (FOUNDATION, "Fundacja"),
    (NON_GOV, "Organizacja pozarządowa"),
    (LOCAL_COLLECTION, "Zbiórka lokalna")
}


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    institution_type = models.SmallIntegerField(choices=INSTITUTION_CHOICE, default=FOUNDATION)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    class Meta:
        ordering = ['pick_up_date']

    def __str__(self):
        return f'{self.quantity} dla {self.institution.name} od {self.user.first_name} {self.user.last_name}'

    quantity = models.SmallIntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=128)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=128)
    zip_code = models.CharField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_comment = models.TextField()
    user = models.ForeignKey(User, null=True, default=None, on_delete=models.CASCADE)
    is_taken = models.BooleanField(default=False)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Donation


class UserRegister(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label="Imię")
    last_name = forms.CharField(max_length=30, required=True, label="Nazwisko")
    email = forms.EmailField(max_length=254, required=True, label="E-mail")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({
                "placeholder": field.label,
            })


class UserLoginForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}))


class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = [
            'categories',
            'quantity',
            'institution',
            'address',
            'phone_number',
            'city',
            'zip_code',
            'pick_up_date',
            'pick_up_time',
            'pick_comment'
        ]


class UserSettings(forms.Form):
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Imię'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Nazwisko'}))
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'placeholder': 'E-mail'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz hasło'}))

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        if cleaned_data['password'] != cleaned_data['password_repeat']:
            self.add_error('password', 'Hasła nie są identyczne')
            self.add_error('password_repeat', 'Hasła nie są identyczne')
            raise forms.ValidationError("Podano różne hasła")
        return cleaned_data

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers import serialize

from datetime import datetime

from .models import (
    Category,
    Donation,
    Institution,
    FOUNDATION,
    NON_GOV,
    LOCAL_COLLECTION
)
from .forms import UserRegister, UserLoginForm, DonationForm, UserSettings


class LadingPageView(View):
    def get(self, request):
        return render(request, 'main/lading_page_view.html', {
            'total_bags_count': sum([x.quantity for x in Donation.objects.all()]),
            'total_institution_count': Donation.objects.all().distinct('institution').count(),
            'help_foundations': Institution.objects.filter(institution_type=FOUNDATION),
            'help_gov': Institution.objects.filter(institution_type=NON_GOV),
            'help_local_collection': Institution.objects.filter(institution_type=LOCAL_COLLECTION),
        })


class AddDonationView(LoginRequiredMixin, View):
    login_url = "/login"

    def get(self, request):
        step = request.GET.get('step')
        if step is not None:
            if step == '1':
                categories = Category.objects.all()
                result = [[category.id, category.name] for category in categories]
                return JsonResponse(result, safe=False)
            elif step == '3':
                institution_set = Institution.objects.filter(
                    categories__pk__in=request.GET.getlist('categories[]')).distinct()
                result = [
                    [institution.id, institution.name, institution.description]
                    for institution in institution_set
                ]
                return JsonResponse(result, safe=False)
        return render(request, 'main/add_donation_view.html', {
            'form_category': Category.objects.all(),
        })

    def post(self, request):
        post_data = {**request.POST}
        donation = Donation.objects.create(
            quantity=post_data['bags'][0],
            institution=Institution.objects.get(pk=post_data['organization'][0]),
            address=post_data['address'][0],
            phone_number=post_data['phone'][0],
            city=post_data['city'][0],
            zip_code=post_data['postcode'][0],
            pick_up_date=datetime.fromisoformat(post_data['data'][0]).date(),
            pick_up_time=datetime.strptime(post_data['time'][0], '%H:%M').time(),
            pick_comment=post_data['more_info'][0],
            user=request.user
        )
        for category in post_data['categories']:
            cat = Category.objects.get(pk=category)
            donation.categories.add(cat)
            donation.save()

        return render(request, 'main/donation_confirm.html')


class LoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, 'main/login_view.html', {
            'form': form
        })

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            try:
                user_db = User.objects.get(email=form.cleaned_data['email'])
                user = authenticate(request, username=user_db.username, password=form.cleaned_data['password'])
                if user is not None:
                    login(request, user)
                    return redirect('landing-page')
            except User.DoesNotExist:
                return redirect('register-page')
        return render(request, 'main/login_view.html', {
            'form': form,
            'msg': 'Błędne hasło'
        })


class RegisterView(View):
    def get(self, request):
        form = UserRegister
        return render(request, 'main/register_view.html', {
            'form': form,
        })

    def post(self, request):
        form = UserRegister(request.POST)
        if form.is_valid():
            if form.cleaned_data['password1'] == form.cleaned_data['password2']:
                del form.cleaned_data['password2']
                form.cleaned_data['password'] = form.cleaned_data.pop('password1')
                User.objects.create_user(**form.cleaned_data)
                return redirect('login-page')

        return render(request, 'main/register_view.html', {
            'form': form,
            'msg': "Password didn't match"
        })


def logout_view(request):
    logout(request)
    return redirect('landing-page')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'main/user_profile.html', {

        })


class UserSettingsView(LoginRequiredMixin, View):
    def get(self, request):
        form = UserSettings(initial={
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
            "email": request.user.email,

        })
        return render(request, 'main/user_settings.html', {
            'form': form
        })
    def post(self,request):
        form = UserSettings(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=request.user.id)
            user.check_password(form.cleaned_data.get('password'))
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
        print('nie valid')
        return render(request, 'main/user_settings.html', {
            'form': form
        })

def takenConfirm(request):
    if request.method == "POST":
        if not request.user.is_anonymous:
            id = request.POST.get('id', None)
            if id is not None:
                donation = get_object_or_404(Donation, pk=id)
                donation.is_taken = True
                donation.save()
                return JsonResponse({'Done': True})

main/templates/main/add_donation_view.html
{% extends 'base/base_view.html' %}

{% block content %}
    <header class="header--form-page">
        {% include 'base/base_nav.html' %}
        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Oddaj rzeczy, których już nie chcesz<br/>
                    <span class="uppercase">potrzebującym</span>
                </h1>

                <div class="slogan--steps">
                    <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
                    <ul class="slogan--steps-boxes">
                        <li>
                            <div><em>1</em><span>Wybierz rzeczy</span></div>
                        </li>
                        <li>
                            <div><em>2</em><span>Spakuj je w worki</span></div>
                        </li>
                        <li>
                            <div><em>3</em><span>Wybierz fundację</span></div>
                        </li>
                        <li>
                            <div><em>4</em><span>Zamów kuriera</span></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <section class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            <form method="post">
            {% csrf_token %}
                <!-- STEP 1: class .active is switching steps -->
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>

                    {% for category in form_category %}
                        <div class="form-group form-group--checkbox">
                            <label>
                                <input
                                        type="checkbox"
                                        name="categories"
                                        value="{{ category.id }}"
                                />
                                <span class="checkbox"></span>
                                <span class="description">{{ category.name }}</span>
                            </label>
                        </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="number" name="bags" step="1" min="1"/>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>


                <!-- STEP 4 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>

                    <div class="form-group form-group--checkbox">
                        <label>
                            <input type="radio" name="organization" value="old"/>
                            <span class="checkbox radio"></span>
                            <span class="description">
                  <div class="title">Fundacja “Bez domu”</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc dla osób nie posiadających miejsca
                    zamieszkania
                  </div>
                </span>
                        </label>
                    </div>

                    <div class="form-group form-group--checkbox">
                        <label>
                            <input type="radio" name="organization" value="old"/>
                            <span class="checkbox radio"></span>
                            <span class="description">
                                  <div class="title">Fundacja “Dla dzieci"</div>
                                  <div class="subtitle">
                                    Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji
                                    życiowej.
                                  </div>
                                </span>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 5 -->
                <div data-step="4">
                    <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Ulica <input type="text" name="address"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Miasto <input type="text" name="city"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Kod pocztowy <input type="text" name="postcode"/>
                                </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Numer telefonu <input type="phone" name="phone"/>
                                </label>
                            </div>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Data <input type="date" name="data"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Godzina <input type="time" name="time"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Uwagi dla kuriera
                                    <textarea name="more_info" rows="5"></textarea>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 6 -->
                <div data-step="5">
                    <h3>Podsumowanie Twojej darowizny</h3>

                    <div class="summary">
                        <div class="form-section">
                            <h4>Oddajesz:</h4>
                        </div>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="submit" class="btn">Potwierdzam</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

main/templates/main/donation_confirm.html
{% extends 'base/base_view.html' %}

{% block content %}
    <header class="header--form-page">
      {% include 'base/base_nav.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>
{% endblock %}

main/templates/main/lading_page_view.html
{% extends 'base/base_view.html' %}
{% load static %}
{% block content %}
    <header class="header--main-page">
        {% include 'base/base_nav.html' %}
        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Zacznij pomagać!<br/>
                    Oddaj niechciane rzeczy w zaufane ręce
                </h1>
            </div>
        </div>
    </header>
    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>{{ total_bags_count }}</em>
                <h3>Oddanych worków</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum
                    tempora!</p>
            </div>

            <div class="stats--item">
                <em>{{ total_institution_count }}</em>
                <h3>Wspartych organizacji</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate
                    quas quam.</p>
            </div>

        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'register-page' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt
                libero optio esse quisquam illo omnis.</p>
            <img src="{% static 'images/signature.svg' %}" class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>

            <ul class="help--slides-items">
                {% for foundation in help_foundations %}
                    <li>
                        <div class="col">
                            <div class="title">Fundacja "{{ foundation.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ foundation.description }}</div>
                        </div>
                        <div class="col">
                            <div class="text">
                                {% for category in foundation.categories.all %}
                                    {{ category.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
            </ul>
            -->
        </div>


        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur
                accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
                quos suscipit corporis!
            </p>
            <ul class="help--slides-items">
                {% for organization in help_gov %}
                    <li>
                        <div class="col">
                            <div class="title">Organizacja "{{ organization.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ organization.description }}</div>
                        </div>
                        <div class="col">
                            <div class="text">
                                {% for category in organization.categories.all %}
                                    {{ category.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
            </ul>
            -->
        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci
                partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
            <ul class="help--slides-items">
                {% for local in help_local_collection %}
                    <li>
                        <div class="col">
                            <div class="title">{{ local.name }}</div>
                            <div class="subtitle">{{ local.description }}</div>
                        </div>
                        <div class="col">
                            <div class="text">
                                {% for category in local.categories.all %}
                                    {{ category.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
            </ul>
            -->
        </div>
    </section>
{% endblock %}

main/templates/main/login_view.html
{% extends 'base/base_view.html' %}

{% block content %}
    <header>
        {% include 'base/base_nav.html' %}
    </header>

    <section class="login-page">
        <h2>Zaloguj się</h2>
        <form method="post">
            {% csrf_token %}
            {% if msg %}
                <h1>{{ msg }}</h1>
            {% endif %}
            <div class="form-group">
                {{ form.email.errors }}
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password.errors }}
                {{ form.password }}
                <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url 'register-page' %}" class="btn btn--without-border">Załóż konto</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>
{% endblock %}

main/templates/main/user_profile.html
{% extends 'base/base_view.html' %}

{% block content %}
    <header>
        {% include 'base/base_nav.html' %}
    </header>

    <section class="login-page">
        <h3>Username: {{ request.user.username }}</h3>
        <h3>Imie: {{ request.user.first_name }}</h3>
        <h3>Nazwisko: {{ request.user.last_name }}</h3>
        <h3>E-mail: {{ request.user.email }}</h3>

        <table style="width:100%">
            <tr>
                <th>Ilość worków</th>
                <th>Organizacja</th>
                <th>Kategorie</th>
                <th>Data odebrania</th>
                <th>Odebrano?</th>
            </tr>
            {% for donation in request.user.donation_set.all|dictsort:"is_taken" %}
                <tr>
                    <td>{{ donation.quantity }}</td>
                    <td>{{ donation.institution.name }}</td>
                    <td>
                        {% for category in donation.categories.all %}
                            {{ category.name }},
                        {% endfor %}
                    </td>
                    <td>{{ donation.pick_up_date }}</td>
                    <td>
                        {% if donation.is_taken == 0 %}
                            <button class="btn-confirm" data-id="{{ donation.id }}">Oznacz jako odebrano</button>
                            {% else %}Tak
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                <td colspan="4">Brak przekazanych darów</td>
                </tr>
            {% endfor %}
        </table>
    </section>

{% endblock %}